name: Deploy Running Page

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # 强制 Node 24

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.12'

      - name: Clean dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build project
        run: npm run build

      - name: Check build output
        run: |
          if [ ! -d "./dist" ]; then
            echo "dist directory not found! Build failed."
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions'
          user_email: 'github-actions@github.com'
          force_orphan: true  # 强制覆盖